services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    image: adult-train:naif
    volumes:
      - ./artifacts:/artifacts

  serve:
    build:
      context: .
      dockerfile: Dockerfile.serve.opt
    image: ghcr.io/ssabiridrissi-rgb/adult-serve:opt6
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/artifacts
    depends_on:
      train:
        condition: service_completed_successfully
